version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/theojeannes/Documents/IsaDevOps/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
    image: jenkins/ssh-agent:jdk17
    container_name: agent
    user: root
    privileged: true
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCYAjXv7mOVTddJN9BtjrLVS/awPyKIesL8gM+nwhE5HiXRTF+PocLPmUttwKiX0Hb5iq6aguZAinQsK9rHnzrJZmU88MskzbcJg57ATkD16TxX7lxR3mpBchhn/bwnNEvZUA3u6kAw13rjzFWghDSoFDfYtLoSCmptewWe6b0c511gxrOx30OJ1bTTMZBNqY3+rYl8/F4j/B75AB6pnlUmcOS8HziVUiaDIEOn43kytpSWzeZn2yAX6gcak61ynpullkXB8ez4khPdL4K2ZZVtQGE0jkZgc8NIUxH7PqGAgQ89YSeT9EsL8RrU2oP8SOwoeq3eQHgRrOI62MnCILEY0xAPPJYnheLgji9RWiBxSVYbHT/vo0GQ+1dTb8h8c9dunxy7igFy1wUou2r6yPvcOtouKX3khrEfkTdHqnvdOLAPGQPU96Xpcm99b9/cDEZs0pxiZc6oOZB0DtFZDjbqVKCCmkW+XIyuc+s8jp2gVqYN7vi+mq2yaecB3uCfvvU= theojeannes@pop-os
