version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/theojeannes/Documents/IsaDevOps/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  agent:
    image: jenkins/ssh-agent:jdk17
    container_name: agent
    user: root
    privileged: true
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCSfctyPqSw2IjROZ/SS6a7ue/HrOh/EGZwXZs8Ph5/z6d/6Kp08hExbvlFEXxok1t4HscjYrP+cDIyoTuYO1NuowTzXdATyK/4hHoAMcx1tnxYLgWxjXBooRb7gYFCNifkNYGUZL+kZvT9HYU8I5JLRMidLebTzPuWznSsZBwJqXuWyqtcJdgmEtAAzdwSxzJ7eK/riOL+XzVu7h35TPwDSHaq4ozipdL0E04Tt9KW87CxB+Mkym12D8LQsf4anxWK4+BGG27PIjNmCAMCmG7V5athqzOmrE+5hOMbQaeVFUVVDi6sbT7wYZz6DGuMw22LByxS+LNfaKPqGZ3QJOdz5JVHTkXUuFskRh0HDWm2LswqKRXHhy1Fn/fEYyjlrce6qJ6+nhM101KnZ9zdvlU75EqDu/DfbeTZPgv+J6Cps/ex66yyCWeXWJ8ZI5ySYg0tF8hPBzM8r7wydX8e8lDjdo6oA5uSGr4BmYlrthTVySqhtYE6mUlhMA757V+7zps= theojeannes@pop-os
